CREATE TABLE ALUNO (

	RA VARCHAR(20) PRIMARY KEY NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	E_MAIL VARCHAR(45) NOT NULL,
	TELEFONE VARCHAR(30) NOT NULL
);

CREATE TABLE ORIENTADOR (

	MATRICULA VARCHAR(20) PRIMARY KEY NOT NULL,
	NOME VARCHAR(50) NOT NULL, 
	E_MAIL VARCHAR(45) NOT NULL,
	TELEFONE VARCHAR(45) NOT NULL
);

CREATE TABLE ORIETACAO (

	ALUNO_RA VARCHAR(20) NOT NULL,
	ORIENTADOR_MATRICULA VARCHAR(20) NOT NULL,
	DIA_ORIENTACAO DATE NOT NULL,
	HORA_ORIENTACAO TIME(3),
	DESCRICAO VARCHAR(200),
	CONSTRAINT PRIMARY KEY(ALUNO_RA, ORIENTADOR_MATRICULA),
	INDEX ALUNO_has_ORIENTADOR_FKIndex1(ALUNO_RA),
	INDEX ALUNO_has_ORIENTADOR_FKIndex2(ORIENTADOR_MATRICULA)
	/*CONSTRAINT FOREIGN KEY AL(ALUNO_RA) REFERENCES ALUNO(RA),
	CONSTRAINT FOREIGN KEY ORI(ORIENTADOR_MATRICULA) REFERENCES ORIENTADOR(MATRICULA)*/
);