 


CREATE TABLE AMBULATORIOS
(
	NROA INT PRIMARY KEY NOT NULL,
	ANDAR NUMERIC(3) NOT NULL,
	CAPACIDADE SMALLINT
	
);
CREATE TABLE MEDICOS 
(	CODM INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(40) NOT NULL,
	IDADE SMALLINT NOT NULL,
	ESPECIALIDADE CHAR(20),
	CPF VARCHAR(15) UNIQUE NOT NULL,
	CIDADE VARCHAR(30),
	NROAMB INT,
	CONSTRAINT FOREIGN KEY FK_AMBULATARIO(NROAMB)
		REFERENCES AMBULATORIOS(NROA)

);
CREATE TABLE PACIENTES
(	CODP INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(40) NOT NULL,
	IDADE SMALLINT NOT NULL,
	CIDADE CHAR(30),
	CPF VARCHAR(15) UNIQUE,
	DOENCA VARCHAR(40) NOT NULL
);

CREATE TABLE FUNCIONARIOS
(	CODF INT PRIMARY KEY NOT NULL,
	NOME VARCHAR(40) NOT NULL,
	IDADE SMALLINT,
	CIDADE CHAR(30),
	CPF VARCHAR(15) UNIQUE,
	SALARIO DECIMAL(8,2),
	CARGO VARCHAR(20)
);

CREATE TABLE CONSULTAS 
(	CODM INT NOT NULL,
	CODP INT,
	DATA DATE,
	HORA TIME,
	CONSTRAINT PRIMARY KEY(CODM,DATA,HORA),
	CONSTRAINT FOREIGN KEY FK_MEDICO(CODM)
		REFERENCES MEDICOS(CODM),
	CONSTRAINT FOREIGN KEY FK_PACIENTE(CODP)
		REFERENCES PACIENTES(CODP)

);

